const DEMO_ACTION_TYPES = {
  DEMO_SET_LOCAL_AUDIO_URL: "DEMO_SET_LOCAL_AUDIO_URL",
  DEMO_GET_AUTO_CHUNK_API_CALL: "DEMO_GET_AUTO_CHUNK_API_CALL",
  DEMO_GET_AUTO_CHUNK_API_SUCCESS: "DEMO_GET_AUTO_CHUNK_API_SUCCESS",
  DEMO_GET_AUTO_CHUNK_API_FAILURE: "DEMO_GET_AUTO_CHUNK_API_FAILURE",
  /**
   * set if the page is upload or
   */
  DEMO_SET_STATE: "DEMO_SET_STATE",
  DEMO_RESET: "DEMO_RESET",
};
export default DEMO_ACTION_TYPES;
